version: "1"
rules:                      # Array of rules
  - base: v7            # Required. Target branch
    upstream: IntellectualSites:v7    # Required. Must be in the same fork network.
    mergeMethod: rebase  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
label: ":arrow_heading_down: pull"  # Optional
